// @ts-check

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '基本信息',
      collapsed: false,
      items: [
        'intro',
      ],
    },
    {
      type: 'category',
      label: '从这里开始',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial-basics',
        },
      ],
    },
    {
      type: 'category',
      label: '上手案例',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial-extras',
        },
      ],
    },
  ],
};

export default sidebars;
